export const POPULATE_BOARD = 'POPULATE_BOARD';
export const SHUFFLE_IMAGES = 'SHUFFLE_IMAGES';
export const CREATE_CARDS = 'CREATE_CARDS';
export const ACTIVATE_CARD = 'ACTIVATE_CARD';
export const DEACTIVATE_ALL_CARDS = 'DEACTIVATE_ALL_CARDS';
export const CHANGE_BOARD_SIZE = 'CHANGE_BOARD_SIZE';
export const RESET_BOARD = 'RESET_BOARD';
